analyzer:
  errors:
    always_use_package_imports: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Style rules
    prefer_single_quotes: true
    always_use_package_imports: true
    directives_ordering: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    
    # Error rules
    avoid_print: true
    avoid_unused_constructor_parameters: true
    avoid_web_libraries_in_flutter: true
    
    # Flutter rules
    use_build_context_synchronously: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    
    # Performance rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    
    # Documentation rules
    public_member_api_docs: false
    
    # Naming rules
    non_constant_identifier_names: true
    constant_identifier_names: true
    library_names: true
    file_names: true